### ISSUE TITLE
Pratica 6

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-6-practica-de-productividad-busgs-pull-request-entrevista_gestion-de-proyecto#1]
[practica 6.pdf](https://github.com/user-attachments/files/17237758/practica.6.pdf)

**Comment by josealfredo79** [comment]
Calificacion..???

**Comment by yanet-02** [comment]
Portada: 25%
Procedimiento: 25%
Figuras, ilustraciones y figuras: 25%
Resultados y conclusiones: 25%

Calificación: 100/100 = 20/20

**Comment by josealfredo79** [comment]
Favor de evaluar bien  @yanet-02 falta la creacion de la rama, pull request, el merge...el cierre automatico de la incidencia

**Comment by JeroRoque** [comment]
Portada: 25%
Procedimiento: 17%
Figuras, ilustraciones y figuras: 25%
Resultados y conclusiones: 25%

Calificación: 18.4/20
 Muy bien, solo faltó mostrar las comparaciones en donde se visualiza tus modificaciones .

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
